version: '3.7'
services:
  mongodb:
    build: ./mongodb_replica
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_REPLICA_HOST: 127.0.0.1
      MONGO_REPLICA_PORT: 27017
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
  # nestjs:
  #   build:
  #     dockerfile: ./Dockerfile
  #   restart: always
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - mongodb
      
volumes:
  mongodb_data: